---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - 
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - На веб-сайте должна быть реализована возможность ознакомиться с условиями и порядком оплаты заказа.
  - На веб-сайте должна быть реализована возможность ознакомиться с условиями доставки и возврата товара.
  - На веб-сайте должна быть представлена информация с контакными данными продавца.
  - На сайте должна быть представлена возможность регистрации с указаниями контактных данных клиента, для возможности обратной связи.
  - При смене языка сайта, вся информация должна автоматически переводиться на выбранный язык для удобства ознакомления.
  - При отсутствии  интернета на веб-сайте должно происходить оповещение об этом.
