---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Пользователь должен иметь возможность удалить товар из корзины и продолжить выбирать товары в каталоге.
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты.
  - Пользователь должен иметь возможность видеть каталог товаров  с информацией по названию товара, его рейтингу, цене товара со скидкой и без.
  - Пользователь должен иметь возможность видеть на странице товара его название, рейтинг, цену товара со скидкой и без.
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Cайт должен работать без перезагрузки страницы.
  - Сайт должен сохранять содержимое корзины до закрытия страницы браузера.
  - В каталоге товаров выводится название товара, рейтинг, цена со скидкой и без.
implicit:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - На веб-сайте должна быть реализована возможность ознакомиться с условиями и порядком оплаты заказа.
  - На веб-сайте должна быть реализована возможность ознакомиться с условиями доставки и возврата товара.
  - На веб-сайте должна быть представлена информация с контакными данными продавца.
  - На сайте должна быть представлена возможность регистрации с указаниями контактных данных клиента, для возможности обратной связи.
  - На сайте должна быть представлена клиентам возможность оставить отзыв о товаре.
  - При смене языка сайта, вся информация должна автоматически переводиться на выбранный язык для удобства ознакомления.
  - При смене языка сайта, стоимость товаров должна автоматически конвертироваться и отображаться в валюте выбранной страны. 
  - При отсутствии  интернета на веб-сайте должно происходить оповещение об этом.
